language: java
env:
  global:
  - GITHUB_REPO=symbiote-h2020/SemanticManager
  - secure: A53YXztid9DYLDPqhJDRFM7nsZl9QntUisR3GVRW/TLD2vwa6pSLQgoTUWTi26VivQP+oksAxa4pvaR+YoSQ9sphHmlqv56hWJs1dPJdGD+hn2IoyRliIBBJowDHNWgu6d3kfm3Lk+y2lWiUV1jFeCC5vVRYbeNUpSc/9KyqWy4pl9SSpvcFiZi5fNhPViGsUx92PXs8wDVk0lYSGiJySeLIMmYvp2pEjIeGL8EbhMrPr+lM4seHLhBDjDwF5r/Evq+q4e3lIyWMahfthmED5h8LNNEtMXUjQB5x0CMjf4Wf9wOmMPTal2yFJsgAUavGr3qU9v4Q2p8j2Y3a2HuQReFzpx6TUt2Cf2MV1eWmoSmHT0aCESLvqVRfsw7xzBGzYT3hY92vlpenchtfa+ZRha3wU+ANL12HCcovn/I4+b2XvlnpPjFThNEuPBzJEYVxtutMlSIyUdLBBXgPFWJ0+pDzA5Z1SxrtlZtkHF/dRPf9Z9n0V3JZelKI1sZWKfwsxJR2HzAIqWpBUKwojnhpHacB/nScuw5d5tGVxORSvrjAInh7gDrP9fe88r8v/J8KPYmgmepljA8ZGPEifms5h7Bls8bEI53cj8QkBt5nJl+sQseUXJB4ImGtqCrCN9/L8cO6IuNVwWVAa8qI/Az1HsENqsqBvpgb5vCXwb2nsLs=
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- chmod a+x merge_script.sh
- "./merge_script.sh"
after_success:
- chmod a+x pushing_script.sh
- "./pushing_script.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
